---
language: ruby
cache: bundler
rvm:
- 2.5.6
- 2.6.4
- 3.0.0
services:
- mysql
- postgresql
env:
- DB=mysql2
- DB=pg
- DB=sqlite3
gemfile:
- gemfiles/gemfile_52.gemfile
- gemfiles/gemfile_60.gemfile
- gemfiles/gemfile_61.gemfile

# rails 5.2
jobs:
  include:
    - env: DB=pg
      rvm: 2.5.6
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=mysql2
      rvm: 2.5.6
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=sqlite3
      rvm: 2.5.6
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=pg
      rvm: 2.6.4
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=mysql2
      rvm: 2.6.4
      gemfile: gemfiles/gemfile_52.gemfile
    - env: DB=sqlite3
      rvm: 2.6.4
      gemfile: gemfiles/gemfile_52.gemfile

before_install:
- 'echo ''gem: --no-ri --no-rdoc --no-document'' > ~/.gemrc'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- sh -c "if [ '$DB' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS virtual_attributes;' ; psql -c ' CREATE DATABASE virtual_attributes;' ; fi"
- sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'DROP DATABASE IF EXISTS virtual_attributes; CREATE DATABASE virtual_attributes;'; fi"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
