---
language: ruby
cache: bundler
rvm:
- 2.4.1
- 2.5.5
services:
- postgresql
- mysql
env:
- DB=sqlite3
- DB=pg
- DB=mysql2
gemfile:
- gemfiles/virtual_attributes_50.gemfile
- gemfiles/virtual_attributes_51.gemfile
- gemfiles/virtual_attributes_52.gemfile
before_install:
- 'echo ''gem: --no-ri --no-rdoc --no-document'' > ~/.gemrc'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- sh -c "if [ '$DB' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS virtual_attributes;' ; psql -c ' CREATE DATABASE virtual_attributes;' ; fi"
- sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'DROP DATABASE IF EXISTS virtual_attributes; CREATE DATABASE virtual_attributes;'; fi"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
