sqlite3:
  adapter: sqlite3
  database: ":memory:"
  encoding: utf8

postgresql:
  adapter: postgresql
  database: virtual_attributes
  encoding: utf8
  host: localhost
  min_messages: WARNING
  pool: 3
  schema_search_path: public
  username: postgres
  wait_timeout: 5

mysql2:
  adapter: mysql2
  database: virtual_attributes
  encoding: utf8
  host: 127.0.0.1
  pool: 3
  username: root
  wait_timeout: 5
